// Generated by `npm run probe` on 2026-09-08.
// Do not edit by hand: these numbers are measurements, not intentions.
//
// A deployment listed on the network is not necessarily still served. This file records
// what actually answered, so the catalogue never advertises a tool that cannot run.

export const VERIFIED_AT = "2026-09-08";

/** Governance subgraphs that returned data when last probed. */
export const LIVE_GOVERNANCE_PROTOCOLS = [
  "ampleforth",
  "compound",
  "cryptex",
  "ens",
  "euler",
  "gitcoin",
  "hifi",
  "hop",
  "ousd",
  "pooltogether",
  "radicle",
  "rarible",
  "reflexer",
  "threshold",
  "uniswap",
] as const;

/** Listed on the network but serving nothing, kept so the gap stays visible. */
export const UNSERVED_GOVERNANCE_PROTOCOLS = [
  "aave",
  "angle",
  "dydx",
  "maker",
  "silo",
  "truefi",
  "unlock",
] as const;

/** Lending deployments that answered, by chain. */
export const LIVE_LENDING_BY_CHAIN: Record<string, number> = {
  "ethereum": 24,
  "avalanche": 7,
  "polygon": 3,
  "arbitrum": 9,
  "base": 4,
  "optimism": 3
};

export const LIVE_LENDING_TOTAL = 50;
export const INDEXED_LENDING_TOTAL = 59;
