// Generated by `npm run probe` on 2026-09-11.
// Do not edit by hand: these numbers are measurements, not intentions.
//
// A deployment listed on the network is not necessarily still served. This file records
// what actually answered, so the catalogue never advertises a tool that cannot run.

export const VERIFIED_AT = "2026-09-11";

/** Governance subgraphs that returned data when last probed. */
export const LIVE_GOVERNANCE_PROTOCOLS = [
  "ampleforth",
  "compound",
  "cryptex",
  "ens",
  "euler",
  "gitcoin",
  "hifi",
  "hop",
  "ousd",
  "pooltogether",
  "radicle",
  "rarible",
  "reflexer",
  "threshold",
  "uniswap",
] as const;

/** Listed on the network but serving nothing, kept so the gap stays visible. */
export const UNSERVED_GOVERNANCE_PROTOCOLS = [
  "aave",
  "angle",
  "dydx",
  "maker",
  "silo",
  "truefi",
  "unlock",
] as const;

/** Lending deployments that answered, by chain. */
export const LIVE_LENDING_BY_CHAIN: Record<string, number> = {
  "ethereum": 23,
  "arbitrum": 9,
  "bsc": 5,
  "avalanche": 7,
  "fantom": 0,
  "polygon": 3,
  "base": 4,
  "optimism": 3,
  "blast": 0,
  "gnosis": 3,
  "harmony": 0,
  "moonriver": 0,
  "aurora": 0,
  "linea": 0,
  "moonbeam": 0,
  "near": 0,
  "scroll": 1,
  "xlayer": 0,
  "zksync-era": 0
};

export const LIVE_LENDING_TOTAL = 58;
export const INDEXED_LENDING_TOTAL = 91;

/** Chains with at least one lending deployment answering. Offered as inputs. */
export const LIVE_LENDING_CHAINS = [
  "ethereum",
  "arbitrum",
  "bsc",
  "avalanche",
  "polygon",
  "base",
  "optimism",
  "gnosis",
  "scroll",
] as const;
