import dotenv from "dotenv";
import fs from "node:fs";
import { governancePower } from "@/lib/tools/governance-power";
import { lendingRates } from "@/lib/tools/lending-rates";
import { GOVERNANCE_PROTOCOLS, SUPPORTED_CHAINS } from "@/lib/graph/deployments";

dotenv.config({ path: ".env.local" });
dotenv.config();

/**
 * Measures what the router can actually answer, and writes it down.
 *
 * A subgraph existing in the network's deployment list does not mean it is still
 * served: seven of the twenty-two governance subgraphs return nothing at all. Claiming
 * them on the catalogue would be advertising tools that 502 on the first call, so the
 * catalogue reads from what this probe verified rather than from what was indexed once.
 *
 * Run with `npm run probe` when adding a chain or protocol, and commit the result.
 */

const OUTPUT = "lib/graph/verified.ts";

async function main() {
  console.log("probing governance subgraphs…");

  // Sequentially, with a retry. Firing all twenty-two at the gateway at once gets some
  // of them throttled, and a throttled protocol is indistinguishable from a dead one —
  // which would quietly delete working tools from the catalogue.
  const governance: { protocol: string; live: boolean }[] = [];

  for (const protocol of GOVERNANCE_PROTOCOLS) {
    let live = false;
    for (let attempt = 0; attempt < 2 && !live; attempt++) {
      try {
        await governancePower(protocol);
        live = true;
      } catch {
        if (attempt === 0) await new Promise((resolve) => setTimeout(resolve, 400));
      }
    }
    governance.push({ protocol, live });
  }

  const liveProtocols = governance.filter((g) => g.live).map((g) => g.protocol).sort();
  const dead = governance.filter((g) => !g.live).map((g) => g.protocol).sort();

  console.log(`  live: ${liveProtocols.length}/${governance.length}`);
  if (dead.length > 0) console.log(`  not served: ${dead.join(", ")}`);

  console.log("probing lending deployments…");

  const lending: Record<string, number> = {};
  let scannedTotal = 0;

  for (const chain of SUPPORTED_CHAINS) {
    // USDC is the one asset every lending market on every chain lists, which makes it
    // the probe that reaches the most deployments.
    const result = (await lendingRates("USDC", chain)) as {
      scanned: number;
      responded: number;
    };
    lending[chain] = result.responded;
    scannedTotal += result.scanned;
    console.log(`  ${chain.padEnd(11)} ${result.responded}/${result.scanned}`);
  }

  const respondedTotal = Object.values(lending).reduce((sum, n) => sum + n, 0);

  const file = `// Generated by \`npm run probe\` on ${new Date().toISOString().slice(0, 10)}.
// Do not edit by hand: these numbers are measurements, not intentions.
//
// A deployment listed on the network is not necessarily still served. This file records
// what actually answered, so the catalogue never advertises a tool that cannot run.

export const VERIFIED_AT = "${new Date().toISOString().slice(0, 10)}";

/** Governance subgraphs that returned data when last probed. */
export const LIVE_GOVERNANCE_PROTOCOLS = [
${liveProtocols.map((p) => `  "${p}",`).join("\n")}
] as const;

/** Listed on the network but serving nothing, kept so the gap stays visible. */
export const UNSERVED_GOVERNANCE_PROTOCOLS = [
${dead.map((p) => `  "${p}",`).join("\n")}
] as const;

/** Lending deployments that answered, by chain. */
export const LIVE_LENDING_BY_CHAIN: Record<string, number> = ${JSON.stringify(lending, null, 2)};

export const LIVE_LENDING_TOTAL = ${respondedTotal};
export const INDEXED_LENDING_TOTAL = ${scannedTotal};
`;

  fs.writeFileSync(OUTPUT, file);
  console.log(`\nwrote ${OUTPUT}`);
  console.log(`  governance: ${liveProtocols.length} protocols`);
  console.log(`  lending:    ${respondedTotal} of ${scannedTotal} deployments`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
